pipelines:
  - name: generic_integration_example
    steps:
    - name: step_1
      type: Bash
      configuration:
        integrations:
          - name: myCredentials
      execution:
        onExecute:
          - printenv int_myCredentials_username
          - printenv int_myCredentials_password
